services:
  - type: web
    name: webshop-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 4242
      - key: NODE_OPTIONS
        value: "--max-old-space-size=2048"